version: 2
jobs:
    build:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - run: make build
            - run: make test

    deploy_staging:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on staging server
                  command: HOSTNAME=$STAGING_HOSTNAME PORT=$STAGING_PORT HELP_CENTER_URL="https://${STAGING_HOSTNAME}/" make deploy

    deploy_production:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - add_ssh_keys
            - run:
                  name: Deploy on production server
                  command: HOSTNAME=$PROD_HOSTNAME PORT=$PROD_PORT ONLY_PREVIOUS_MONTH_UPDATES=true make deploy
            - run:
                  name: Push announcements for the communication pannel of the PIM
                  command: make push-announcements
workflows:
    version: 2
    pull_request:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - master

    deployment:
        jobs:
            - deploy_production:
                  filters:
                      branches:
                          only: master
            - deploy_staging:
                  filters:
                      branches:
                          only: master

    # feature announcements of the previous months should be deployed automatically the 5th day of the month in the helpcenter
    # before this date, the announcements are not generated and so not pushed in production
    # in staging, all announcements are published as soon as a PR is merged, so there is no need to redeploy it every night
    nightly:
        triggers:
            - schedule:
                  cron: "0 2 * * *"
                  filters:
                      branches:
                          only:
                              - master
        jobs:
            - deploy_production
